task-2: implementation
alla-blinkova/python-ta-course pull request #2
Opened 2021-03-25 08:32 UTC by alla-blinkova

2021-03-25 13:07 UTC, alpakhomov requested changes

2021-03-25 13:07 UTC, alpakhomov commented on Lecture_2_Collections_homework/hw1.py
> +import re
https://www.python.org/dev/peps/pep-0008/#imports в питоне есть требования к порядку сортировки импортов. Чтобы не думать об этом, можно использовать утилиту isort https://pypi.org/project/isort/ Ее можно запускать из командной строки или пользоваться каким-либо плагином для редактора кода (например в vscode можно просто в настройках указать сортировку импортов при сохранении)
В эту же сторону - стоит использовать форматтер кода, блэк https://pypi.org/project/black/ Он так же при сохранении отформатирует кода (например сам поменяет кавычки на двойные, чтобы все было одинаково)
Например в линуксе/макос такая комнда 
```sh
isort --profile black --check . && black --check .
```
поправит все импорты и отформатирует все (на винде должно быть аналогично)
Это касается всех файлов

2021-03-25 13:07 UTC, alpakhomov commented on Lecture_2_Collections_homework/hw1.py
> +    return bool(regexp.match(date))
```suggestion
    return re.match(r'.*\d{4}-\d{2}-\d{2}$', date)
```
тут можно не использовать compile (все равно ведь будет компайлиться каждый раз при вызове функции; смысл compile в том чтобы один раз скомпилить и потом много раз применять). Ну и можно сразу возвращать, не кастить в bool Метод match вернет либо матч объект, либо None - и в соответствующем if этот None превратится в False, а любой не пустой объект в True https://docs.python.org/3/library/stdtypes.html#truth-value-testing

2021-03-25 13:07 UTC, alpakhomov commented on Lecture_2_Collections_homework/hw1.py
> +                    file_output.write("{} {}\n".format(line.rstrip(), validator.__name__))
```suggestion
```
Переделай плз на f-strings https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals Ф-стринги обычно быстрее чем .format, да и читаются лучше. Бывают кейсы когда они не сработают (например при большой вложенности скобок) но по умолчанию в современном питоне стоит использовать именно их

2021-03-25 13:07 UTC, alpakhomov commented on Lecture_2_Collections_homework/hw1.py
> +    return filepath_out
```suggestion
```
Из функции нужно вернуть абсолютный путь (например у меня локально тесты сейчас не проходят, потому что не находят файл). Используй https://docs.python.org/3/library/os.path.html#module-os.path там есть нужный метод

2021-03-25 13:07 UTC, alpakhomov commented on Lecture_2_Collections_homework/hw5.py
> +    all_range_symbols = [chr(i) for i in range(*args_with_codes)]
Тут все ок, но можно не генерить всю последовательность символов, а сразу фильтровать только нужные

2021-03-28 16:48 UTC, alla-blinkova commented on Lecture_2_Collections_homework/hw1.py
> +    return filepath_out
Fixed

2021-03-28 16:49 UTC, alla-blinkova commented on Lecture_2_Collections_homework/hw1.py
> +import re
Done

2021-03-28 16:50 UTC, alla-blinkova commented on Lecture_2_Collections_homework/hw1.py
> +    return bool(regexp.match(date))
Fixed

2021-03-28 16:50 UTC, alla-blinkova commented on Lecture_2_Collections_homework/hw1.py
> +                    file_output.write("{} {}\n".format(line.rstrip(), validator.__name__))
Fixed

2021-03-28 16:50 UTC, alla-blinkova commented on Lecture_2_Collections_homework/hw5.py
> +    all_range_symbols = [chr(i) for i in range(*args_with_codes)]
Done

2021-03-28 17:14 UTC, alpakhomov approved these changes
Все ок, можно мержить

2021-03-29 10:37 UTC, merged